# Site settings
title: 'Ryan Domingue is a web designer and developer living in Seattle, Washington'
description: 'Ryan Domingue works with HTML, CSS and JavaScript, and spends his time learning and creating. Ryan loves coffee and cannot be trusted around cookies.'
permalink: /notes/:title.html

# Development/Serve
host: ryandomingue.dev # local vhost
port: 8080

# Build settings
markdown: kramdown
highlighter: rouge
url: http://ryandomingue.com
exclude: [Gruntfile.js, package.json, node_modules, README.md, LICENSE, _drafts/README.md]
timezone: America/Los_Angeles

# sass settings
sass:
  sass_dir: _scss
  style: expanded
  precision: 4

# kramdown settings
kramdown:
  auto_ids:      false
  smart_quotes:  lsquo,rsquo,ldquo,rdquo

# Misc constants
blogroll: /notes/
heading_blog: Notes
heading_projects: Selected Projects

twitter_username: goodguyry
github_username:  goodguyry
github_base_url: http://github.com/goodguyry
codepen_username:  goodguyry

stuff: nonsense
