# Site settings
title: 'Ryan Domingue is a UX Developer living in Seattle, Washington'
description: 'Ryan Domingue works with HTML, CSS, and JavaScript, and spends his time learning and creating. Ryan loves coffee and cannot be trusted around cookies.'
permalink: /notes/:title.html
blogroll: /notes/

# Development/Serve
port: 8080

# Build settings
markdown: kramdown
highlighter: rouge
url: http://goodguyry.http
include: [_pages, _files]
exclude:
  - _drafts/README.md
  - LICENSE
  - node_modules
  - package-lock.json
  - package.json
  - README.md
  - Vagrantfile
  - vm-config.yaml
  - '*.sublime-*'
timezone: America/Los_Angeles

# kramdown settings
kramdown:
  auto_ids: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
